stages:
  pull-kml:
    cmd:
      - wget http://www.bfro.net/app/AllReportsKMZ.aspx
      - mv AllReportsKMZ.aspx data/raw/
      - unzip -o data/raw/AllReportsKMZ.aspx -d data/raw/
    outs:
      - data/raw/AllReportsKMZ.aspx:
          persist: true # Theoretically not necessary, but just in case it fails, we don't want to delete it.
      - data/raw/doc.kml:
          persist: true
    always_changed: true

  save-existing-reports:
    cmd:
      - touch data/raw/bfro_reports.json
      - cp data/raw/bfro_reports.json data/raw/bfro_reports_orig.json
    outs:
      - data/raw/bfro_reports_orig.json
    always_changed: true

  pull-new-reports:
    cmd:
      - cd bfro/bfro_scrape &&
        scrapy crawl bfro_reports
        --output $(dvc root)/data/raw/bfro_reports_new.json
        --output-format jsonlines
    outs:
      - data/raw/bfro_reports_new.json
    always_changed: true

  merge-reports:
    cmd:
      - python bfro/bfro_union_reports.py
        data/raw/bfro_reports_orig.json
        data/raw/bfro_reports_new.json
        data/raw/bfro_reports.json
    deps:
      - bfro/bfro_union_reports.py
      - data/raw/bfro_reports_orig.json
      - data/raw/bfro_reports_new.json
    outs:
      - data/raw/bfro_reports.json:
          persist: true

  extract-locations-from-kml:
    cmd:
      - python bfro/bfro_locations.py
        data/raw/doc.kml
        data/raw/bfro_locations.csv
    deps:
      - bfro/bfro_locations.py
      - data/raw/doc.kml
    outs:
      - data/raw/bfro_locations.csv

  geocode-reports:
    cmd:
      - python bfro/bfro_report_join.py
        data/raw/bfro_locations.csv
        data/raw/bfro_reports.json
        data/interim/bfro_reports_geocoded.csv
    deps:
      - bfro/bfro_report_join.py
      - data/raw/bfro_locations.csv
      - data/raw/bfro_reports.json
    outs:
      - data/interim/bfro_reports_geocoded.csv

  pull-weather:
    cmd:
      - python bfro/bfro_report_weather.py
        data/interim/bfro_reports_geocoded.csv
        data/cache/weather_cache.csv
    deps:
      - bfro/bfro_report_weather.py
      - data/interim/bfro_reports_geocoded.csv
    outs:
      - data/cache/weather_cache.csv:
          persist: true

  add-weather:
    cmd:
      - python bfro/bfro_weather_join.py
        data/interim/bfro_reports_geocoded.csv
        data/cache/weather_cache.csv
        data/processed/bfro_reports_geocoded.csv
    deps:
      - bfro/bfro_weather_join.py
      - data/interim/bfro_reports_geocoded.csv
      - data/cache/weather_cache.csv
    outs:
      - data/processed/bfro_reports_geocoded.csv
