name: bfro-sightings-data
channels:
  - defaults
dependencies:
  - pip
  - python=3.9
  - pip:
      - click
      - elasticsearch>=5,<6
      - ipython
      - lxml
      - numpy
      - pandas
      - pygeohash>=1,<2
      - python-dotenv
      - scrapy==1.4.0
      - toolz
      - black
      - flake8
      - loguru
      - dvc[gs]
